spring:  
  datasource:
    url: jdbc:h2:tcp://localhost/~/testdb
    username: '{cipher}AQAUasqNt9Ij/pQRcG8ckwmg8RfJg2hqbMSyWDfcKzBVKwdKKiJFlTIdDSSqqEO6mUOn6kDtaP/T6fRNSj+ZGms/nKTeL0ZhDMQuvTScaZwEtUylxfrcfM4iyFKAooaNbWvOhFSXOjZUTT/ufKVz5BW23+QVCbBIKLWc07bKSnXXLET1jt4G9FM56y3d6iw8BF4JqVpNzMTwB9+jVp3Cc0a2xkN5ceRHobHuYOhq8LT3qBkqNaFjEUC66mjZq5d6pMQEcRmaqM58Yz7il+D5tYorqhphlcFMRA+u7fdlpHUIZ6Btq1UC342lrsTYQQO26eOZNGRnqZSNYkBqO/2CpP2vm+9CouMJ53CGE1yydBSnWnVE28dwOBroDBanvw1RPvA='
#    username: '{cipher}30c4ccc17ca92c62ff5038951e631626d1a28e7385c9f2e2a1a5d5f1471d4b01'
    password: 
    driver-class-name: org.h2.Driver
    
token:
  expiration_time: 86400000
  secret: '{cipher}AQBMYuYTsjYmr2yrrXmp4On4+vBjsRJUdxN4JjTSnoWVqLd3chT6f4fJAIfM7FWa4hymWnc1NHgodeAk7IetgyjGsq1BFir0w8YVoj5igJMUNcw0gi8roQQknQZTesqoxxMAYigseoYixom9ST6Be8AxuR3FGNzDeNC3W2kpa/87o3fFTw4uyym52/uswQpz1cOtehMnVGRuOccizULtX5YMNH/8huh25k5/joDJXLpPknr7P9YTf0pwfH2IOBu70e2W+4QsO48IvQRPNYT+s5KSi93OQRHrMVQF8P5aBur8UYpelw5Oq8XTmN1zc5I2BlPXy7XmdNetlNFIey8jRwoyjv++JPr0GjJqyuWt29rgAqtY2saq0T0DmTiwEVqE3+6E/ExMmD70CzrLfZxovKWe'
  
gateway:
  ip: 192.168.0.112